#!/bin/bash

mkdir -p logs

args=${@:-"l r R a t"}
options=`./powerset $args`
dirs=(".." ".")

echo_infos()
{
    echo `tput setaf 5`
    echo avec l\(es\) options $1
	echo pour le\(s\) folder\(s\) $2
	echo -n `tput setaf 2`	
}

go()
{
	eval $1 -$3 $4 | cat -e > logs/`echo $3$4`$2
}
 
for option in $options
do
	for dir in $dirs
	do
		echo_infos $option $dir
		go ls logVrai $option $dir
		go ../ft_ls logMoi $option $dir
		diff logs/`echo $option$dir`logMoi logs/`echo $option$dir`logVrai
	done
done
