#!/bin/bash

rm -rf ../logs
mkdir -p ../logs

options="l R r a t"
options=`./powerset $options`
dirs=". ~/libft"

echo_infos()
{
    echo `tput setaf 5`
    echo avec l\(es\) options $1
	echo pour le\(s\) folder\(s\) $2
	echo -n `tput setaf 2`	
}

go()
{
	echo evaluating : $1 -$3 $4
	eval "$1 -$3 $4 | cat -e" > ../logs/`echo $3`$2
}
 
for option in $options
do
	for dir in $dirs
	do
#		echo_infos $option $dir
		go ls logVrai $option $dir
		go ../ft_ls logMoi $option $dir
		diff ../logs/`echo $option`logVrai ../logs/`echo $option`logMoi
		if [ $? == 0 ] ; then
			echo 😀
		else
			echo 😡
		fi
	done
done
